
platform :ios, '9.0'

target 'JYPProduct' do

  pod 'Masonry'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'IQKeyboardManager' # 键盘
  pod 'ReactiveObjC'      # 详解 http://www.jianshu.com/p/0845b1a07bfa
  pod 'SVProgressHUD'     
  pod 'AFNetworking'
  pod 'YYModel'
  pod 'LYEmptyView'       # https://github.com/dev-liyang/LYEmptyView
  
  
end
